import { plotHelp } from "./handle/plot.js"

export function help(): string {
  return [
    "aq  Aquin framework CLI (train / eval / fleet)",
    "",
    "A run is recipe.yaml + runtime dirs (paths.artifacts, default artifacts/). Docs: https://aquinf03.github.io/aq/documentation/ · SDK: pip install -e ./aq",
    "Agent chat is a separate package: axi (install separately).",
    "",
    "  aq help                 this text",
    "  aq version              framework version (-v / --version; version --verbose for paths)",
    "  aq update               install the latest release (same as curl install.sh | bash)",
    "  aq login                open aquin.app/aq/?view=desktop&client=cli, then paste the code",
    "  aq login --token <aq-…>  paste an existing CLI token",
    "  aq login --check        who is signed in",
    "  aq logout [email]       drop the active (or that) account",
    "  aq switch [email]       list or switch ~/.aquin accounts",
    "  aq init                 new run folder aq-run (or -new1, -new2, …)",
    "  aq init <name>          same, named folder (also -newN if taken)",
    "  aq data hash [dir] [--snapshot]  hash + inspect data.path (table → data/revision.json)",
    "  aq train [dir] [--tracker] [--system] [--grads] [--capture-code] [--capture-env[=lock|full]]",
    "                          --system → CPU/GPU/mem/disk/net beside loss (metrics + TUI)",
    "                          --grads → grad/param norms (HF Trainer + torch loops)",
    "                          --capture-code → artifacts/code/tree.tgz",
    "                          --capture-env → artifacts/env/ (lock=pip freeze; full=7z venv)",
    "                          recipe capture.system / capture.grads / capture.code / capture.env · AQ_CAPTURE_*",
    "                          recipe guard.safety / guard.leak = opt-in fail-closed watches",
    "  aq eval [dir] [name] [--ckpt name] [--tracker] [--system] [--suite|--no-suite]",
    "                          --suite → classical metrics+plots (tabular default on)",
    "                          recipe eval.extra: [cost] → scorers.py:cost on the same board",
    "  aq checkpoint [dir] [--keep name]  list or copy last to name",
    "  aq serve [dir] [prompt] [--image path] [--ckpt name] [--max-tokens n] [--temperature t]",
    "  aq diff [dir] [<a> <b>]     compare run records (files, not screenshots)",
    "  aq plot [dir] [metrics|jobs|runs|samples|table|eval|all]  charts / table TUI / eval suite",
    "  aq status [dir]            last run, eval, metrics",
    "  aq track [dir]             browse runs / --follow live metrics",
    "  aq track [dir] <run_id> [-f]  show run · optional live tail filtered by run_id",
    "  aq add ssh [name]         register an SSH place (prompts)",
    "  aq add pool [name] [m…]   pool of SSH places (picks a free box)",
    "  aq places [--tag k=v]       list places (+ live load; --probe capacity)",
    "  aq tag place|job …          labels on places & jobs (governance)",
    "  aq launch [dir] [--on <place>] [--no-setup] [--shell] [--port N] [-- <cmd>]",
    "                          sync folder → place + setup aq (laptop); --on optional",
    "  aq go [place] [--port N]  open SSH to last launch (resync if local folder)",
    "  aq sync [dir] [--on p]    push/update folder → place (no shell; laptop only)",
    "  aq shutdown [place] [--wipe]  stop jobs + clear session",
    "  aq port <N> [--on p] [--bg]  SSH tunnel (expose remote UI on laptop)",
    "  aq jobs …                remote jobs on a place/pool",
    "  aq jobs run|train|eval|serve [--name N] [--on p] [--tag k=v] [--gpu N] [--devices 0,1] [--port N] [--json]",
    "  aq jobs sweep [--shard N] [--grid k=a,b] [--on p] [--gpu N] [--manage] -- <cmd>",
    "  aq jobs status|logs|pull|down|recover|watch|manage <id>",
    "  aq jobs list [--tag k=v] [--all] [--json]   filter / dump machine JSON",
    "  aq queue add <name> --on <place|pool>   push / worker / drain / move",
    "  aq queue push <name> [--priority N] -- <cmd> · aq queue worker [name]",
    plotHelp(),
    "",
    "Agent (separate install):",
    "  axi                 chat · ask · provider · doctor · spawn",
    "",
    "init writes:",
    "  recipe.yaml     path map (edit by hand and/or via SDK)",
    "  example.py      aquin sample (YAML-first; define optional)",
    "  artifacts/      default runtime dir (override with paths.artifacts)",
    "",
    "Kernel (Python): aq writes <artifacts>/request.json, reads <artifacts>/result.json.",
  ].join("\n")
}
