import { plotHelp } from "./handle/plot.js"

export function help(): string {
  return [
    "aq  Aquin CLI",
    "",
    "A run is recipe.yaml + artifacts/. Docs: https://aq.aquin.app/docs · SDK: pip install -e ./aq",
    "",
    "  aq                      agent chat (TTY)",
    "  aq agent                same",
    "  aq chat list            previous chats",
    "  aq chat last            resume the latest",
    "  aq chat <id>           resume that chat",
    "  aq ask [dir] <prompt>   one-shot answer (no chat UI)",
    "  aq ask --json [dir] <prompt>",
    "  aq help                 this text",
    "  aq version              framework version (-v / --version; version --verbose for paths)",
    "  aq update               install the latest release (same as curl | bash)",
    "  aq login                open aq.aquin.app/?view=desktop&client=cli, then paste the code",
    "  aq login --token <aq-…>  paste an existing CLI token",
    "  aq login --check        who is signed in",
    "  aq logout [email]       drop the active (or that) account",
    "  aq switch [email]       list or switch ~/.aquin accounts",
    "  aq provider             list openai / anthropic / grok / ollama",
    "  aq provider <name>      save key (hidden) and use it",
    "  aq provider use <name>  switch",
    "  aq init                 new run folder aq-run (or -new1, -new2, …)",
    "  aq init <name>          same, named folder (also -newN if taken)",
    "  aq data hash [dir] [--snapshot]  hash recipe data.path",
    "  aq train [dir]          fit; write checkpoints + artifacts/metrics.jsonl",
    "                          recipe guard.safety / guard.leak = opt-in fail-closed watches",
    "  aq eval [dir] [name] [--ckpt name]  score evals/<name> (all evals/ if omitted)",
    "  aq checkpoint [dir] [--keep name]  list or copy last to name",
    "  aq serve [dir] [prompt] [--image path] [--ckpt name] [--max-tokens n] [--temperature t]",
    "  aq diff [dir] [<a> <b>]     compare run records (files, not screenshots)",
    "  aq plot [dir] [metrics|jobs|runs|all]  matplotlib charts from artifacts",
    "  aq status [dir]            last run, eval, metrics",
    "  aq doctor [dir]           health check (cli, provider, run, skills, mcp)",
    "  aq add ssh [name]         register an SSH place (prompts)",
    "  aq add pool [name] [m…]   pool of SSH places (picks a free box)",
    "  aq places                 list places (+ resources; --probe refreshes)",
    "  aq launch [dir] --on <place> [--no-setup] [-- <cmd>]",
    "                          sync folder → place, setup aq, open SSH",
    "  aq go [place]             re-SSH to last launch (resync if local folder)",
    "  aq jobs                   list remote jobs on last place",
    "  aq jobs run|train|eval|serve [--on p] [--nodes N] [--gpu N] [--json]",
    "  aq jobs status|logs|pull|down|recover <id>   (--rank K · recover --next|--same)",
    "  aq queue add <name> --on <place|pool>   push / worker / drain / move",
    "  aq queue push <name> [--priority N] -- <cmd> · aq queue worker [name]",
    "  aq spawn agent [dir] -- <prompt>  start a worker agent",
    "  aq spawn agent --kill -- <prompt>  critic: cheapest disproof",
    "  aq spawn list [dir]       worker agents",
    "  aq spawn log [dir] <id>  that agent's log",
    "  aq spawn cancel [dir] <id>",
    plotHelp(),
    "",
    "init writes:",
    "  recipe.yaml     path map (edit by hand and/or via SDK)",
    "  example.py      aquin sample (YAML-first; define optional)",
    "  artifacts/      runtime output (checkpoints, metrics, …)",
    "",
    "Kernel (Python): aq writes artifacts/request.json, reads artifacts/result.json.",
  ].join("\n")
}
